#!/usr/bin/python3

import RPi.GPIO as GPIO
import time
import sys

# Uncomment to get values for lab5_2
"""
DOT         = 0.1
DASH        = 0.2
CHAR_GAP    = 0.3
WORD_GAP    = 0.4
SYMBOL_GAP  = 0.1
"""

#Uncomment to get values for lab5_3
# """
DOT         = 0.06
DASH        = 0.12
CHAR_GAP    = 0.18
WORD_GAP    = 0.24
SYMBOL_GAP  = 0.06 
# """ 

class ArgumentError(Exception):
    pass

if len(sys.argv) != 3:
    raise ArgumentError(r'Error: Invalid number of arguments. Please enter initiate this program like `sudo python3 LED.py <NUMBER OF MESSAGES SENT> "<MESSAGE>"` ')

class morse_translator():
    def __init__(self, message, message_number = 1):
        self.morse_code_dict = {
            'A': '.-'   ,
            'B': '-...' ,
            'C': '-.-.' ,
            'D': '-..'  ,
            'E': '.'    ,
            'F': '..-.' ,
            'G': '--.'  ,
            'H': '....' ,
            'I': '..'   ,
            'J': '.---' ,
            'K': '-.-'  ,
            'L': '.-..' ,
            'M': '--'   ,
            'N': '-.'   ,
            'O': '---'  ,
            'P': '.--.' ,
            'Q': '--.-' ,
            'R': '.-.'  ,
            'S': '...'  ,
            'T': '-'    ,
            'U': '..-'  ,
            'V': '...-' ,
            'W': '.--'  ,
            'X': '-..-' ,
            'Y': '-.--' ,
            'Z': '--..' ,

            '0': '-----',
            '1': '.----',
            '2': '..---',
            '3': '...--',
            '4': '....-',
            '5': '.....',
            '6': '-....',
            '7': '--...',
            '8': '---..',
            '9': '----.'
        }
        self.morse_code_durations = {
            '.'     : DOT     ,
            '-'     : DASH    ,
            '/'     : WORD_GAP,
            ' '     : CHAR_GAP,
        }
        self.number_of_messages = message_number
        self.message = message
        self.translation = self.translate_message()

    def translate_message(self):
        morse_translation = ''
        for word in self.message.split():
        
            for index, letter in enumerate(word):
                morse_translation += self.morse_code_dict[letter.upper()]
                if index != len(word) - 1:
                    morse_translation += ' '

            morse_translation += '/'
        
        morse_translation = morse_translation.rstrip(' /')
        morse_translation += '/'
        return morse_translation
    
    def send_morse_message(self):
        print(f'Sending the message "{self.message}" translated to "{self.translation}"')
        for i in range(self.number_of_messages):
        
            try:
                for letter in self.translation:
                    if letter in ['.', '-']:
                        print(f"Current Symbol: {letter} | Intended to turn on for: {self.morse_code_durations[letter]}")
                        GPIO.output(4, GPIO.HIGH)
                        time.sleep(self.morse_code_durations[letter])
                        GPIO.output(4, GPIO.LOW)
                        time.sleep(SYMBOL_GAP) 
                    
                    elif letter in ['/', ' ']:
                        print(f"Current Symbol: {letter} | Intended to turn off for: {self.morse_code_durations[letter]}")
                        GPIO.output(4, GPIO.LOW)
                        time.sleep(self.morse_code_durations[letter])

            except KeyboardInterrupt:
                print("\nExiting translation early")
                GPIO.output(4, GPIO.LOW)
                break
        
        print("Done sending morse code")
        GPIO.output(4, GPIO.HIGH)
        time.sleep(SYMBOL_GAP)
        GPIO.output(4, GPIO.LOW)

    def print_translation():
        print(f'The message "{self.message}" translates to "{self.translation}"')

def init_GPIO(self, GPIO_PIN = 4):
    GPIO.setmode(GPIO.BCM)
    GPIO.setwarnings(False)
    GPIO.setup(GPIO_PIN, GPIO.OUT)

if __name__ == '__main__':
    init_GPIO(4)
    messager = morse_translator(sys.argv[2], int(sys.argv[1]))
    messager.send_morse_message()
